produtosPrecos = ('pão', 1, 'banana', 3.50, 'Melão', 8.5, 'Pão de queijo', 15.87)
print('LISTAGEM DE PRODUTOS')
print(f'{produtosPrecos[0]}.............. R${produtosPrecos[1]}')
print(f'{produtosPrecos[2]}........... R${produtosPrecos[3]}')
print(f'{produtosPrecos[4]}............ R${produtosPrecos[5]}')
print(f'{produtosPrecos[6]}.... R${produtosPrecos[7]}')