valor = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(valor)}')
print(f'Só tem espaços? {valor.isspace()}')
print(f'É um número? {valor.isnumeric()}')
print(f'É alfabético? {valor.isalpha()}')
print(f'É alfanumérico? {valor.isalnum()}')
print(f'Esta em maiuscula? {valor.isupper()}')
print(f'Esta em minuscula? {valor.islower()}')
print(f'Esta capitalizada? {valor.istitle()}')
print( 5//2)
